version: '2.1'
services:
  app:
    image: mozilla/sbt:11.0.8_1.3.13
    ports:
     - 9000:9000
     - 5005:5005
    working_dir: /app
    links:
     - db
     - ganache
    volumes:
     - .:/app
    volumes_from:
     - sbt
    env_file:
     - ./conf/dev.env
    stdin_open: true
    command: sbt -Dsun.net.http.allowRestrictedHeaders=true -jvm-debug 5005 runWithMigrate

  db:
    image: postgres:10
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=muttniks
      - POSTGRES_USER=muttniks
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=

  jobs:
    build:
      context: .
      dockerfile: Dockerfile.lein
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ./app/contracts/Adoption.json:/app/jobs/src/java/contracts/Adoption.json
    volumes_from:
     - lein
    links:
      - redis
      - app
      - ganache
    env_file:
      - ./jobs/dev.env
    command: lein run

  redis:
    image: redis:3
    expose:
      - "6379"
    ports:
      - 6379:6379

  sbt:
    image: centos:7
    volumes:
     - ~/.ivy2:/root/.ivy2:rw
     - ~/.ivy2:/home/docker/.ivy2:rw
     - ~/.sbt:/root/.sbt:rw
     - ~/.sbt:/home/docker/.sbt:rw

  lein:
    image: centos:7
    volumes:
      - ~/.m2:/root/.m2:rw

  truffle:
      image: tlazenka/muttniks-truffle:1.0
      volumes:
        - .:/app
        - /app/sol/node_modules
        - ./truffle.js.docker:/app/sol/truffle.js
      links:
        - ganache
      tty: true

  ganache:
      build:
          context: .
          dockerfile: Dockerfile.ganache
      expose:
        - "7545"
      ports:
        - "7545:7545"
      command: ganache-cli --hostname=0.0.0.0 --port 7545 --deterministic --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"

  react:
      build:
          context: .
          dockerfile: Dockerfile.react
      ports:
        - 3000:3000
      links:
        - app
        - jobs
        - ganache
      volumes:
        - .:/app
        - /app/ui/node_modules
        - ./sol/build/contracts/Adoption.json:/app/ui/src/build/contracts/Adoption.json
        - ./react.env:/app/ui/.env
      environment:
        - NODE_ENV=development
        
  client:
    build:
        context: .
        dockerfile: Dockerfile.swift
    volumes:
      - .:/app
    environment:
      - API_BASE_URL=http://app:9000/
      - CACHE_BASE_URL=http://jobs:5000/
      - TEST_CLIENT_REQUEST_TIMEOUT_SECONDS=30
      - TEST_CLIENT_RESOURCE_TIMEOUT_SECONDS=60
      - TEST_CACHE_POLL_DURATION_SECONDS=30
      - TEST_ACCOUNT=0x5aeda56215b167893e80b4fe645ba6d5bab767de
      - TEST_PRIVATE_KEY=8d5366123cb560bb606379f90a0bfd4769eecc0557f1b362dcae9012b548b1e5
      - TEST_PET_ID=3
      - TEST_ALLOW_ADOPTION_ERRORS=1
    working_dir: /app/client/Fetcher
    command: swift test 
    links:
      - app  
      - jobs

  web3j:
      build:
          context: .
          dockerfile: Dockerfile.web3j
      volumes:
        - .:/code
