FROM rust:1.33.0-stretch

ENV APP_HOME /app/cli
WORKDIR $APP_HOME

COPY ./cli/Cargo.toml .
COPY ./cli/Cargo.lock .
COPY ./cli/src/main.rs ./src/main.rs

RUN cargo fetch

COPY . .

CMD ["cargo", "run"]
