FROM node:7.10.1-wheezy

RUN npm install -g truffle@4.1.8

ENV APP_HOME /app/sol
WORKDIR $APP_HOME

COPY ./sol/package.json .
COPY ./sol/package-lock.json .
RUN npm install
RUN npm install -E openzeppelin-solidity@1.9.0

COPY . .
