version: '2'
services:
  app:
    image: ysihaoy/scala-play:2.12.3-2.6.2-sbt-0.13.15
    ports:
     - 9000:9000
     - 5005:5005
    working_dir: /app
    links:
     - db
     - ganache
    volumes:
     - .:/app
    volumes_from:
     - sbt
    env_file:
     - ./conf/dev.env
    stdin_open: true
    command: sbt -Dsun.net.http.allowRestrictedHeaders=true -jvm-debug 5005 runWithMigrate

  db:
    image: postgres:10
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=muttniks
      - POSTGRES_USER=muttniks
      - POSTGRES_PASSWORD=
      
  jobs:
    build:
      context: .
      dockerfile: Dockerfile.lein
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ./app/contracts/Adoption.json:/app/jobs/src/java/contracts/Adoption.json
    volumes_from:
     - lein
    links:
      - redis
      - app
      - ganache
    env_file:
      - ./jobs/dev.env
    command: lein run

  redis:
    image: redis:3
    expose:
      - "6379"
    ports:
      - 6379:6379

  sbt:
    image: centos:7
    volumes:
     - ~/.ivy2:/root/.ivy2:rw
     - ~/.ivy2:/home/docker/.ivy2:rw
     - ~/.sbt:/root/.sbt:rw
     - ~/.sbt:/home/docker/.sbt:rw
     
  lein:
    image: centos:7
    volumes:
      - ~/.m2:/root/.m2:rw
     
  truffle:
      build:
          context: .
          dockerfile: Dockerfile.truffle
      volumes:
        - .:/app
        - /app/sol/node_modules
        - ./truffle.js.docker:/app/sol/truffle.js
      links:
        - ganache
      tty: true

  ganache:
      build:
          context: .
          dockerfile: Dockerfile.ganache
      expose:
        - "7545"
      ports:
        - "7545:7545"
      command: ganache-cli --hostname=0.0.0.0 --port 7545 --deterministic --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"

  react:
      build:
          context: .
          dockerfile: Dockerfile.react
      ports:
        - 3000:3000
      links:
        - app
        - jobs
        - ganache
      volumes:
        - .:/app
        - /app/ui/node_modules
        - ./sol/build/contracts/Adoption.json:/app/ui/src/build/contracts/Adoption.json
        - ./react.env:/app/ui/.env
      environment:
        - NODE_ENV=development
        
  web3j:
      build:
          context: .
          dockerfile: Dockerfile.web3j
      volumes:
        - .:/code
          
  firefox:
      build:
          context: .
          dockerfile: Dockerfile.firefox
      shm_size: '2gb'
      ports:
        - "5800:5800"
        - "5900:5900"
      environment:
        - VNC_PASSWORD=password
      links:
        - app
        - jobs
        - ganache
        - react
