[package]
name = "muttniks_cli"
version = "0.1.0"

[dependencies]
getopts = "0.2.18"
reqwest = "0.9.11"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
rand = "0.6.5"
lazy_static = "1.3.0"
