play.http.secret.key=${PLAY_HTTP_SECRET_KEY}


play.filters.hosts.allowed = [
  "localhost",
  "localhost:8080",
  "localhost:9000",
  "127.0.0.1",
  "127.0.0.1:9000",
  "app",
  "app:9000"
]

db.default.driver="org.postgresql.Driver"
db.default.url=${?MUTTNIKS_JDBC_URL}
db.default.username=${?MUTTNIKS_DB_USER}
db.default.password=${?MUTTNIKS_DB_PASSWORD}

play.evolutions.enabled=true
play.evolutions.db.default.enabled=true
play.evolutions.db.default.autoApply=true
play.evolutions.db.default.autoApplyDowns=false
play.evolutions.db.default.useLocks=true
play.evolutions.db.default.autocommit=false

muttniks.postgres.host="localhost"
muttniks.postgres.host=${?MUTTNIKS_DB_HOST}
muttniks.postgres.port=5432
muttniks.postgres.port=${?MUTTNIKS_DB_PORT}
muttniks.postgres.user="muttniks"
muttniks.postgres.user=${?MUTTNIKS_DB_USER}
muttniks.postgres.database="muttniks"
muttniks.postgres.database=${?MUTTNIKS_DB_NAME}
muttniks.postgres.password="muttniks"
muttniks.postgres.password=${?MUTTNIKS_DB_PASSWORD}


muttniks.ethereum.adoption-address=""
muttniks.ethereum.adoption-address=${?ADOPTION_ADDRESS}
muttniks.ethereum.chain-id=31337
muttniks.ethereum.chain-id=${?CHAIN_ID}

muttniks.ethereum.rpc-url="http://127.0.0.1:8545"
muttniks.ethereum.rpc-url=${?ETH_RPC_URL}
muttniks.ethereum.confirmations=12
muttniks.ethereum.confirmations=${?CONFIRMATIONS}
muttniks.ethereum.start-block=0
muttniks.ethereum.start-block=${?START_BLOCK}
muttniks.ethereum.poll-interval=4s
muttniks.ethereum.poll-interval=${?POLL_INTERVAL}
play.application.loader="muttniks.controllers.MuttniksApplicationLoader"
