// flow-typed signature: 7311e8af38d76f42d4fe41f31b89d410
// flow-typed version: <<STUB>>/es6-shim_v^0.35.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-shim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-shim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-shim/es6-sham' {
  declare module.exports: any;
}

declare module 'es6-shim/es6-sham.min' {
  declare module.exports: any;
}

declare module 'es6-shim/es6-shim' {
  declare module.exports: any;
}

declare module 'es6-shim/es6-shim.min' {
  declare module.exports: any;
}

declare module 'es6-shim/Gruntfile' {
  declare module.exports: any;
}

declare module 'es6-shim/test-sham/function' {
  declare module.exports: any;
}

declare module 'es6-shim/test-sham/set-prototype-of' {
  declare module.exports: any;
}

declare module 'es6-shim/test/array' {
  declare module.exports: any;
}

declare module 'es6-shim/test/browser-onload' {
  declare module.exports: any;
}

declare module 'es6-shim/test/browser-setup' {
  declare module.exports: any;
}

declare module 'es6-shim/test/date' {
  declare module.exports: any;
}

declare module 'es6-shim/test/json' {
  declare module.exports: any;
}

declare module 'es6-shim/test/map' {
  declare module.exports: any;
}

declare module 'es6-shim/test/math' {
  declare module.exports: any;
}

declare module 'es6-shim/test/number' {
  declare module.exports: any;
}

declare module 'es6-shim/test/object' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/all' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/evil-promises' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/promises-aplus' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/promises-es6' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/race' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/reject' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/resolve' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/simple' {
  declare module.exports: any;
}

declare module 'es6-shim/test/promise/subclass' {
  declare module.exports: any;
}

declare module 'es6-shim/test/reflect' {
  declare module.exports: any;
}

declare module 'es6-shim/test/regexp' {
  declare module.exports: any;
}

declare module 'es6-shim/test/set' {
  declare module.exports: any;
}

declare module 'es6-shim/test/string' {
  declare module.exports: any;
}

declare module 'es6-shim/test/test_helpers' {
  declare module.exports: any;
}

declare module 'es6-shim/test/worker-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-shim/es6-sham.js' {
  declare module.exports: $Exports<'es6-shim/es6-sham'>;
}
declare module 'es6-shim/es6-sham.min.js' {
  declare module.exports: $Exports<'es6-shim/es6-sham.min'>;
}
declare module 'es6-shim/es6-shim.js' {
  declare module.exports: $Exports<'es6-shim/es6-shim'>;
}
declare module 'es6-shim/es6-shim.min.js' {
  declare module.exports: $Exports<'es6-shim/es6-shim.min'>;
}
declare module 'es6-shim/Gruntfile.js' {
  declare module.exports: $Exports<'es6-shim/Gruntfile'>;
}
declare module 'es6-shim/test-sham/function.js' {
  declare module.exports: $Exports<'es6-shim/test-sham/function'>;
}
declare module 'es6-shim/test-sham/set-prototype-of.js' {
  declare module.exports: $Exports<'es6-shim/test-sham/set-prototype-of'>;
}
declare module 'es6-shim/test/array.js' {
  declare module.exports: $Exports<'es6-shim/test/array'>;
}
declare module 'es6-shim/test/browser-onload.js' {
  declare module.exports: $Exports<'es6-shim/test/browser-onload'>;
}
declare module 'es6-shim/test/browser-setup.js' {
  declare module.exports: $Exports<'es6-shim/test/browser-setup'>;
}
declare module 'es6-shim/test/date.js' {
  declare module.exports: $Exports<'es6-shim/test/date'>;
}
declare module 'es6-shim/test/json.js' {
  declare module.exports: $Exports<'es6-shim/test/json'>;
}
declare module 'es6-shim/test/map.js' {
  declare module.exports: $Exports<'es6-shim/test/map'>;
}
declare module 'es6-shim/test/math.js' {
  declare module.exports: $Exports<'es6-shim/test/math'>;
}
declare module 'es6-shim/test/number.js' {
  declare module.exports: $Exports<'es6-shim/test/number'>;
}
declare module 'es6-shim/test/object.js' {
  declare module.exports: $Exports<'es6-shim/test/object'>;
}
declare module 'es6-shim/test/promise.js' {
  declare module.exports: $Exports<'es6-shim/test/promise'>;
}
declare module 'es6-shim/test/promise/all.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/all'>;
}
declare module 'es6-shim/test/promise/evil-promises.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/evil-promises'>;
}
declare module 'es6-shim/test/promise/promises-aplus.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/promises-aplus'>;
}
declare module 'es6-shim/test/promise/promises-es6.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/promises-es6'>;
}
declare module 'es6-shim/test/promise/race.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/race'>;
}
declare module 'es6-shim/test/promise/reject.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/reject'>;
}
declare module 'es6-shim/test/promise/resolve.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/resolve'>;
}
declare module 'es6-shim/test/promise/simple.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/simple'>;
}
declare module 'es6-shim/test/promise/subclass.js' {
  declare module.exports: $Exports<'es6-shim/test/promise/subclass'>;
}
declare module 'es6-shim/test/reflect.js' {
  declare module.exports: $Exports<'es6-shim/test/reflect'>;
}
declare module 'es6-shim/test/regexp.js' {
  declare module.exports: $Exports<'es6-shim/test/regexp'>;
}
declare module 'es6-shim/test/set.js' {
  declare module.exports: $Exports<'es6-shim/test/set'>;
}
declare module 'es6-shim/test/string.js' {
  declare module.exports: $Exports<'es6-shim/test/string'>;
}
declare module 'es6-shim/test/test_helpers.js' {
  declare module.exports: $Exports<'es6-shim/test/test_helpers'>;
}
declare module 'es6-shim/test/worker-test.js' {
  declare module.exports: $Exports<'es6-shim/test/worker-test'>;
}
