// flow-typed signature: 1440a2832628e9693c50f2403b51c911
// flow-typed version: <<STUB>>/notistack_v^0.3.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notistack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notistack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notistack/build/index' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarContext' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/index' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.styles' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.util' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/constants' {
  declare module.exports: any;
}

declare module 'notistack/build/withSnackbar' {
  declare module.exports: any;
}

declare module 'notistack/demo/App' {
  declare module.exports: any;
}

declare module 'notistack/demo/index' {
  declare module.exports: any;
}

declare module 'notistack/demo/MessageButtons' {
  declare module.exports: any;
}

declare module 'notistack/src/index' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarContext' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/index' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/SnackbarItem.styles' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/SnackbarItem.util' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'notistack/src/utils/constants' {
  declare module.exports: any;
}

declare module 'notistack/src/withSnackbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notistack/build/index.js' {
  declare module.exports: $Exports<'notistack/build/index'>;
}
declare module 'notistack/build/SnackbarContext.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarContext'>;
}
declare module 'notistack/build/SnackbarItem/index.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/index'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.styles.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.styles'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.util.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.util'>;
}
declare module 'notistack/build/SnackbarProvider.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarProvider'>;
}
declare module 'notistack/build/utils/constants.js' {
  declare module.exports: $Exports<'notistack/build/utils/constants'>;
}
declare module 'notistack/build/withSnackbar.js' {
  declare module.exports: $Exports<'notistack/build/withSnackbar'>;
}
declare module 'notistack/demo/App.js' {
  declare module.exports: $Exports<'notistack/demo/App'>;
}
declare module 'notistack/demo/index.js' {
  declare module.exports: $Exports<'notistack/demo/index'>;
}
declare module 'notistack/demo/MessageButtons.js' {
  declare module.exports: $Exports<'notistack/demo/MessageButtons'>;
}
declare module 'notistack/src/index.js' {
  declare module.exports: $Exports<'notistack/src/index'>;
}
declare module 'notistack/src/SnackbarContext.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarContext'>;
}
declare module 'notistack/src/SnackbarItem/index.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/index'>;
}
declare module 'notistack/src/SnackbarItem/SnackbarItem.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/SnackbarItem'>;
}
declare module 'notistack/src/SnackbarItem/SnackbarItem.styles.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/SnackbarItem.styles'>;
}
declare module 'notistack/src/SnackbarItem/SnackbarItem.util.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/SnackbarItem.util'>;
}
declare module 'notistack/src/SnackbarProvider.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarProvider'>;
}
declare module 'notistack/src/utils/constants.js' {
  declare module.exports: $Exports<'notistack/src/utils/constants'>;
}
declare module 'notistack/src/withSnackbar.js' {
  declare module.exports: $Exports<'notistack/src/withSnackbar'>;
}
