// flow-typed signature: bf750ba10ca410b8fc0be8ec3730c8b1
// flow-typed version: <<STUB>>/portis_v^1.2.11/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'portis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'portis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'portis/dist/bundle' {
  declare module.exports: any;
}

declare module 'portis/dist/bundle.min' {
  declare module.exports: any;
}

declare module 'portis/es/index' {
  declare module.exports: any;
}

declare module 'portis/es/provider' {
  declare module.exports: any;
}

declare module 'portis/es/style' {
  declare module.exports: any;
}

declare module 'portis/es/types' {
  declare module.exports: any;
}

declare module 'portis/es/utils' {
  declare module.exports: any;
}

declare module 'portis/lib/index' {
  declare module.exports: any;
}

declare module 'portis/lib/provider' {
  declare module.exports: any;
}

declare module 'portis/lib/style' {
  declare module.exports: any;
}

declare module 'portis/lib/types' {
  declare module.exports: any;
}

declare module 'portis/lib/utils' {
  declare module.exports: any;
}

declare module 'portis/rollup.config' {
  declare module.exports: any;
}

declare module 'portis/rollup.config.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'portis/dist/bundle.js' {
  declare module.exports: $Exports<'portis/dist/bundle'>;
}
declare module 'portis/dist/bundle.min.js' {
  declare module.exports: $Exports<'portis/dist/bundle.min'>;
}
declare module 'portis/es/index.js' {
  declare module.exports: $Exports<'portis/es/index'>;
}
declare module 'portis/es/provider.js' {
  declare module.exports: $Exports<'portis/es/provider'>;
}
declare module 'portis/es/style.js' {
  declare module.exports: $Exports<'portis/es/style'>;
}
declare module 'portis/es/types.js' {
  declare module.exports: $Exports<'portis/es/types'>;
}
declare module 'portis/es/utils.js' {
  declare module.exports: $Exports<'portis/es/utils'>;
}
declare module 'portis/lib/index.js' {
  declare module.exports: $Exports<'portis/lib/index'>;
}
declare module 'portis/lib/provider.js' {
  declare module.exports: $Exports<'portis/lib/provider'>;
}
declare module 'portis/lib/style.js' {
  declare module.exports: $Exports<'portis/lib/style'>;
}
declare module 'portis/lib/types.js' {
  declare module.exports: $Exports<'portis/lib/types'>;
}
declare module 'portis/lib/utils.js' {
  declare module.exports: $Exports<'portis/lib/utils'>;
}
declare module 'portis/rollup.config.js' {
  declare module.exports: $Exports<'portis/rollup.config'>;
}
declare module 'portis/rollup.config.min.js' {
  declare module.exports: $Exports<'portis/rollup.config.min'>;
}
