// flow-typed signature: 6be334873e23a4a52c91c67767c9d563
// flow-typed version: <<STUB>>/react-refetch_v^2.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-refetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-refetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-refetch/lib/components/connect' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/index' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/PromiseState' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/utils/buildRequest' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/utils/checkTypes' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/utils/errors' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/utils/handleResponse' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'react-refetch/lib/utils/shallowEqual' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-refetch/lib/components/connect.js' {
  declare module.exports: $Exports<'react-refetch/lib/components/connect'>;
}
declare module 'react-refetch/lib/index.js' {
  declare module.exports: $Exports<'react-refetch/lib/index'>;
}
declare module 'react-refetch/lib/PromiseState.js' {
  declare module.exports: $Exports<'react-refetch/lib/PromiseState'>;
}
declare module 'react-refetch/lib/utils/buildRequest.js' {
  declare module.exports: $Exports<'react-refetch/lib/utils/buildRequest'>;
}
declare module 'react-refetch/lib/utils/checkTypes.js' {
  declare module.exports: $Exports<'react-refetch/lib/utils/checkTypes'>;
}
declare module 'react-refetch/lib/utils/errors.js' {
  declare module.exports: $Exports<'react-refetch/lib/utils/errors'>;
}
declare module 'react-refetch/lib/utils/handleResponse.js' {
  declare module.exports: $Exports<'react-refetch/lib/utils/handleResponse'>;
}
declare module 'react-refetch/lib/utils/isPlainObject.js' {
  declare module.exports: $Exports<'react-refetch/lib/utils/isPlainObject'>;
}
declare module 'react-refetch/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-refetch/lib/utils/shallowEqual'>;
}
