// flow-typed signature: f1207a62ce8f2583b920c5832efcd401
// flow-typed version: <<STUB>>/react-router-hash-link_v^1.2.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-hash-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-hash-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-hash-link/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-hash-link/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-hash-link/lib/index.js' {
  declare module.exports: $Exports<'react-router-hash-link/lib/index'>;
}
declare module 'react-router-hash-link/src/index.js' {
  declare module.exports: $Exports<'react-router-hash-link/src/index'>;
}
