name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Play! test
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from app app
